version: '3.8'

services:
  veriview-ai:
    build: .
    ports:
      - "5000:5000"
    environment:
      # 환경 변수로 API 키 전달 (권장)
      - AISTUDIOS_API_KEY=${AISTUDIOS_API_KEY}
      - ENVIRONMENT=production
      
      # 선택적 환경 변수들
      - VERIVIEW_AISTUDIOS_API_KEY=${AISTUDIOS_API_KEY}
      - AWS_DEFAULT_REGION=ap-northeast-2
    
    # .env 파일 사용 (대안)
    env_file:
      - .env
    
    volumes:
      # 캐시 디렉토리 마운트
      - ./aistudios_cache:/app/aistudios_cache
      # 로그 디렉토리 마운트
      - ./logs:/app/logs
    
    restart: unless-stopped
    
    # 헬스체크
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
    # 리소스 제한
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

  # Redis 캐시 (선택적)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
